import * as THREE from 'three';import{newMind,think,remember}from'./mind.js';
let ID=1;
function mesh(type){let g=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:type.color}),b=new THREE.Mesh(new THREE.SphereGeometry(.42,14,10),m);b.scale.set(1.3,.7,1);g.add(b);let h=new THREE.Mesh(new THREE.SphereGeometry(.25,12,8),m);h.position.set(0,.04,.45);g.add(h);for(let i=0;i<6;i++){let l=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.65,6),new THREE.MeshStandardMaterial({color:0x17191d}));let s=i%2?1:-1,r=Math.floor(i/2)-1;l.rotation.z=s*1.1;l.rotation.x=r*.3;l.position.set(s*.4,-.12,r*.28);g.add(l)}return g}
export class World{constructor(scene){this.scene=scene;this.entities=[];this.objects=[];this.disaster='calm';this.half=24;this.root=new THREE.Group();scene.add(this.root);this.ground=new THREE.Mesh(new THREE.BoxGeometry(48,.5,48),new THREE.MeshStandardMaterial({color:0x667a52}));this.ground.position.y=-.25;this.root.add(this.ground);this.water=new THREE.Mesh(new THREE.PlaneGeometry(20,14),new THREE.MeshStandardMaterial({color:0x3d91bd,transparent:true,opacity:.5}));this.water.rotation.x=-Math.PI/2;this.water.position.set(-7,.03,5);this.root.add(this.water);let grid=new THREE.GridHelper(48,24,0x82906f,0x4d5b45);grid.position.y=.01;this.root.add(grid)}
v3(x,y,z){return new THREE.Vector3(x,y,z)}groundY(x,z){return 0}
spawn(type,p,mind){let e={id:ID++,name:type.name+' '+ID,type,position:p.clone(),velocity:new THREE.Vector3(),mesh:mesh(type),mind:mind||newMind(),age:0,scale:1,rotationY:0};e.mesh.position.copy(p);e.mesh.userData.entity=e;this.root.add(e.mesh);this.entities.push(e);return e}
add(kind,p){let geo=kind==='food'?new THREE.SphereGeometry(.22,10,8):kind==='shelter'?new THREE.ConeGeometry(1.3,1.5,4):new THREE.BoxGeometry(kind==='water'?3:1.5,kind==='water'?.06:1,kind==='water'?3:1.5);let col=kind==='food'?0xffc64c:kind==='shelter'?0x8c6944:kind==='water'?0x4ca5d0:kind==='terrain'?0x71855b:0x9098a2;let m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:col,transparent:kind==='water',opacity:kind==='water'?.6:1}));m.position.copy(p);m.userData.obj=true;this.root.add(m);let o={kind,position:m.position,mesh:m,scale:1,rotationY:0};m.userData.object=o;this.objects.push(o);return o}
remove(x){let a=x.mind?this.entities:this.objects,i=a.indexOf(x);if(i>=0)a.splice(i,1);this.root.remove(x.mesh)}
update(dt){for(const e of this.entities){think(e,this,dt);let m=e.mind;if(m.goal==='rest'){e.velocity.multiplyScalar(.9);m.needs.energy=Math.min(1,m.needs.energy+dt*.05)}else if(m.target){let d=m.target.clone().sub(e.position),len=d.length();if(len<.7){if(m.goal==='food'){let food=this.objects.find(o=>o.kind==='food'&&o.position.distanceTo(e.position)<1.4);if(food){this.remove(food);m.needs.hunger=Math.max(0,m.needs.hunger-.6);remember(e,'food',e.position,'ate')}}if(m.goal==='social')m.needs.social=Math.min(1,m.needs.social+.4);m.target=null;m.timer=0}else{d.normalize();e.velocity.lerp(d.multiplyScalar(e.type.speed),Math.min(1,dt*4))}}let mv=e.type.move;if(mv==='fly'||mv==='climbfly')e.velocity.y+=(3-e.position.y)*dt*2;else if(mv==='swim'||mv==='surface')e.velocity.y+=(.15-e.position.y)*dt*4;else if(mv==='burrow')e.velocity.y+=(-.15-e.position.y)*dt*4;else if(mv==='hop'){e.velocity.y-=7*dt;if(Math.sin(e.age*8+e.id)>.9)e.velocity.y=2.7}else e.velocity.y+=(.34-e.position.y)*dt*7;if(this.disaster==='wind')e.velocity.x+=dt*2.5;if(this.disaster==='quake'){e.velocity.x+=(Math.random()-.5)*dt*4;e.velocity.z+=(Math.random()-.5)*dt*4}e.position.addScaledVector(e.velocity,dt);e.velocity.multiplyScalar(Math.pow(.86,dt*60));e.position.x=Math.max(-23,Math.min(23,e.position.x));e.position.z=Math.max(-23,Math.min(23,e.position.z));e.mesh.position.copy(e.position);e.mesh.rotation.y=Math.atan2(e.velocity.x,e.velocity.z)+e.rotationY;e.mesh.scale.setScalar(e.scale);e.age+=dt}}
reset(){[...this.entities,...this.objects].forEach(x=>this.remove(x));this.disaster='calm'}}